[
  {
    "name": "type: bug",
    "color": "d73a4a",
    "description": "Something is not working"
  },
  {
    "name": "type: test",
    "color": "00ff00",
    "description": "Something is working as intented"
  },
  {
    "name": "type: richtig gut",
    "color": "0000ff",
    "description": "Something is working very well"
  }
]
