[
  {
    "name": "type: bug",
    "color": "d73a4a",
    "description": "Something is not working"
  },
  {
    "name": "type: richtig gut",
    "color": "0000ff",
    "description": "Something is working very well"
  },
  {
    "name": "type: richtig schlecht",
    "color": "0000ff",
    "description": "Something is working very badly"
  }
]
