[
  {
    "name": "bug",
    "color": "d73a4a",
    "description": "Something isn't working"
  },
  {
    "name": "documentation",
    "color": "0075ca",
    "description": "Improvements or additions to documentation or other"
  },
  {
    "name": "duplicate",
    "color": "cfd3d7",
    "description": "This issue or pull request already exists"
  },
  {
    "name": "enhancement",
    "color": "a2eeef",
    "description": "New feature or request"
  },
  {
    "name": "good first issue",
    "color": "7057ff",
    "description": "Good for newcomers"
  },
  {
    "name": "help wanted",
    "color": "008672",
    "description": "Extra attention is needed"
  },
  {
    "name": "invalid",
    "color": "e4e669",
    "description": "This doesn't seem right"
  },
  {
    "name": "question",
    "color": "d876e3",
    "description": "Further information is requested"
  },
  {
    "name": "wontfix",
    "color": "ffffff",
    "description": "This will not be worked on"
  },
  {
    "name": "P1",
    "color": "fbca04",
    "description": "Emergency Priority"
  },
  {
    "name": "P2",
    "color": "87f125",
    "description": "Standard Priority"
  },
  {
    "name": "P3",
    "color": "0f96fe",
    "description": "Minor Priority"
  }
]
