name: Change Request Infra
description: Request an infrastructure change to an existing system or process.
projects: ["RockLogic | Organisation"]
labels:
  - "Change_Request"
type: Change Request
body:
  - type: markdown
    attributes:
      value: |
        ## Section 1: General Information

  - type: input
    id: name
    attributes:
      label: Requester Name
      description: Full name of the requester.
      placeholder: John Doe
    validations:
      required: true

  - type: dropdown
    id: department
    attributes:
      label: Department/Team
      options:
        - "Infra"
        - "Dev"
        - "IT Admin"
    validations:
      required: true

  - type: dropdown
    id: project_name
    attributes:
      label: Project Name
      options:
        - "RockLogic GmbH"
        - "StereumPlus"
        - "StereumLabs"
        - "Lido"
        - "Fungl"
        - "Centrovox"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Section 2: Change Details

  - type: textarea
    id: change_description
    attributes:
      label: Description of Change
      description: Detailed description of the requested change also includes affected Components Modules.
      placeholder: Describe the requested change and affected components/modules in detail...
    validations:
      required: true

  - type: textarea
    id: reason_for_change
    attributes:
      label: Reason for Change
      description: Business or technical justification for the change.
      placeholder: Explain why this change is necessary...
    validations:
      required: true

  - type: input
    id: deadline
    attributes:
      label: Deadline
      description: Business or technical justification for the change.
      placeholder: DD/MM/YYYY
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Section 3: Security Impact Analysis

  - type: dropdown
    id: security_impact
    attributes:
      label: Is there any potential impact on security?
      options:
        - "Yes"
        - "No"
        - "Unsure (requires further review)"
    validations:
      required: true

  - type: textarea
    id: security_impact_details
    attributes:
      label: Details of Security Impact
      description: Provide details if the change could impact confidentiality, integrity, or availability (e.g., access control, data handling, etc.).
      placeholder: Describe potential security impacts...
    validations:
      required: false

  - type: textarea
    id: mitigation_plan
    attributes:
      label: Mitigation Plan (if applicable)
      description: Steps to mitigate potential risks or vulnerabilities introduced by the change.
      placeholder: Describe mitigation steps...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Section 4: Approvals

  - type: markdown
    attributes:
      value: "### Requester Approval"

  - type: input
    id: requester_name
    attributes:
      label: Name
      placeholder: Full Name
    validations:
      required: false

  - type: input
    id: requester_signature
    attributes:
      label: Signature
      placeholder: Electronic or manual
    validations:
      required: false

  - type: input
    id: requester_date
    attributes:
      label: Date
      placeholder: DD/MM/YYYY
    validations:
      required: false

  - type: markdown
    attributes:
      value: "### Security Team Approval"

  - type: input
    id: security_name
    attributes:
      label: Name
      placeholder: Full Name
    validations:
      required: false

  - type: input
    id: security_signature
    attributes:
      label: Signature
      placeholder: Electronic or manual
    validations:
      required: false

  - type: input
    id: security_date
    attributes:
      label: Date
      placeholder: DD/MM/YYYY
    validations:
      required: false

  - type: markdown
    attributes:
      value: "### Management Approval"

  - type: input
    id: management_name
    attributes:
      label: Name
      placeholder: Full Name
    validations:
      required: false

  - type: input
    id: management_signature
    attributes:
      label: Signature
      placeholder: Electronic or manual
    validations:
      required: false

  - type: input
    id: management_date
    attributes:
      label: Date
      placeholder: DD/MM/YYYY
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Section 5: Post-Implementation Validation (if needed)

  - type: input
    id: validation_date
    attributes:
      label: Validation Date
      placeholder: DD/MM/YYYY
    validations:
      required: false

  - type: input
    id: validation_performed_by
    attributes:
      label: Validation Performed By
      placeholder: Full Name
    validations:
      required: false

  - type: dropdown
    id: security_testing_performed
    attributes:
      label: Security Testing Performed
      options:
        - "Yes"
        - "No"
        - "N/A"
    validations:
      required: false

  - type: textarea
    id: validation_notes
    attributes:
      label: Validation Notes
      description: Summarize findings and confirm whether the change has no adverse security effects / if the Validation is done.
      placeholder: Add validation notes or observations...
    validations:
      required: false
