name: Hardware Request for Existing User
description: Request hardware for Existing Users.
title: "[Hardware Request]: "
projects: ["RockLogic | Organisation"]
labels:
  - "Hardware_Request"
assignees:
  - ahaider-at
  - MarvinsLab
body:
  - type: markdown
    attributes:
      value: |
        Thanks for raising hardware request!

  - type: input
    id: name
    attributes:
      label: User name requesting hardware.
      description: Enter full name of user.
      placeholder: John Doe
    validations:
      required: true

  - type: textarea
    id: hardware_details
    attributes:
      label: Hardware Details
      description: Describe the item(s) you're requesting or include a link to a specific product.
      placeholder: e.g., Laptop, Monitor, Adapter, etc.
    validations:
      required: true
